#PBS -P RDS-SMS-GDT-RW
#PBS -l select=1:ncpus=1:mem=1GB
#PBS -l walltime=80:00:00
#PBS -M yourid@youremail.com
#PBS -m ae
#PBS -o logs/align/workflow.log
#PBS -e logs/align/workflow.error

cd $PBS_O_WORKDIR

module load python/3.10.11
module load star/2.7.9a
module load samtools
module load trimmomatic/0.39
module load bedtools/2.30.0
module load r
module load htslib/1.12
module load tabixpp

snakemake -s workflow/rules/Snakefile_align.smk --nolock --cores 1 all
