config:
  star:
    alignment:
      default:
        - "--outSAMtype BAM Unsorted"
        - "--outSAMattributes NH HI AS NM MD"
        - "--outFilterMultimapNmax 20"
        - "--alignSJoverhangMin 6"
        - "--alignSJDBoverhangMin 6"
        - "--outFilterMismatchNmax 10"      
        - "--outFilterMismatchNoverLmax 0.3"
        - "--alignIntronMin 21"
        - "--alignIntronMax 1000000"
        - "--alignMatesGapMax 0"
        - "--outFilterType BySJout"
        - "--outFilterScoreMinOverLread 0.66"
        - "--outFilterMatchNminOverLread 0.66"
        - "--outSAMstrandField intronMotif"
        - "--outFilterIntronMotifs None"
        - "--alignSoftClipAtReferenceEnds Yes"
        - "--quantMode GeneCounts"
        - "--outSAMunmapped Within"
        - "--chimSegmentMin 12"
        - "--chimJunctionOverhangMin 12"
        - "--chimOutType WithinBAM"
        - "--chimMainSegmentMultNmax 10"
        - "--outSJfilterCountUniqueMin 3 1 1 1"
    genomes:
      hg38_ref:
        data: "/scratch/project/tcr_ml/rna-seq2/resources"
        fasta: "Homo_sapiens_assembly38.fasta"
        gtf: "gencode.v38.annotation.gtf"
        sjdbOverhang: "150"

data:
  fastq: "/QRISdata/Q7444"
  trimmed: "/scratch/project/tcr_ml/rna-seq2/trimmed"

region_of_interest:
  - "chr1:151401724-151460494"
  - "chr1:173823653-173859808"

samples:
  UDCB-01:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-01_22KKVWLT3_TTGTATCAGG-ACAGAGGCCA_L001_R1.fastq.gz"
      r2: "UDCB-01_22KKVWLT3_TTGTATCAGG-ACAGAGGCCA_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
  UDCB-02:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-02_22KKVWLT3_ACAGCGACCA-CAGGAGCTCT_L001_R1.fastq.gz"
      r2: "UDCB-02_22KKVWLT3_ACAGCGACCA-CAGGAGCTCT_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
  UDCB-07:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-07_22KKVWLT3_TCCACACAGA-TTGTCGGATG_L001_R1.fastq.gz"
      r2: "UDCB-07_22KKVWLT3_TCCACACAGA-TTGTCGGATG_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
  UDCB-08:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-08_22KKVWLT3_AAGTGTTAGG-GCTAGTTCCG_L001_R1.fastq.gz"
      r2: "UDCB-08_22KKVWLT3_AAGTGTTAGG-GCTAGTTCCG_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
  UDCB-11:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-11_22KKVWLT3_GATTCTGAAT-AGCGGTGGAC_L001_R1.fastq.gz"
      r2: "UDCB-11_22KKVWLT3_GATTCTGAAT-AGCGGTGGAC_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
  UDCB-14:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-14_22KKVWLT3_GTGCTAGGTT-TGAATATTGC_L001_R1.fastq.gz"
      r2: "UDCB-14_22KKVWLT3_GTGCTAGGTT-TGAATATTGC_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
  UDCB-15:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-15_22KKVWLT3_TAGAGAATAC-TATAGATTCG_L001_R1.fastq.gz"
      r2: "UDCB-15_22KKVWLT3_TAGAGAATAC-TATAGATTCG_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
  UDCB-27:
    genome: "hg38_ref"
    reads:
      r1: "UDCB-27_22KKVWLT3_CACAGCGGTC-ATTCCTATTG_L001_R1.fastq.gz"
      r2: "UDCB-27_22KKVWLT3_CACAGCGGTC-ATTCCTATTG_L001_R2.fastq.gz"
    variations:
      default:
      - "default"
